import type { HexagramListItem } from './hexagram-types'

export const HEXAGRAM_LIST: HexagramListItem[] = [
  {
    number: 1,
    name: '乾',
    pinyin: 'qián',
    symbol: '䷀',
    keywords: ['刚健', '进取', '创造', '领导'],
    fortune: 'great-fortune',
  },
  {
    number: 2,
    name: '坤',
    pinyin: 'kūn',
    symbol: '䷁',
    keywords: ['包容', '柔顺', '厚德', '配合'],
    fortune: 'fortune',
  },
  {
    number: 3,
    name: '屯',
    pinyin: 'zhūn',
    symbol: '䷂',
    keywords: ['初创', '艰难', '萌芽', '坚持'],
    fortune: 'caution',
  },
  {
    number: 4,
    name: '蒙',
    pinyin: 'méng',
    symbol: '䷃',
    keywords: ['启蒙', '学习', '虔诚', '果断'],
    fortune: 'neutral',
  },
  {
    number: 5,
    name: '需',
    pinyin: 'xū',
    symbol: '䷄',
    keywords: ['等待', '耐心', '诚信', '蓄势'],
    fortune: 'fortune',
  },
  {
    number: 6,
    name: '讼',
    pinyin: 'sòng',
    symbol: '䷅',
    keywords: ['争讼', '调解', '适可而止', '预防'],
    fortune: 'caution',
  },
  {
    number: 7,
    name: '师',
    pinyin: 'shī',
    symbol: '䷆',
    keywords: ['领导', '组织', '纪律', '正义'],
    fortune: 'neutral',
  },
  {
    number: 8,
    name: '比',
    pinyin: 'bǐ',
    symbol: '䷇',
    keywords: ['亲附', '合作', '联盟', '真诚'],
    fortune: 'fortune',
  },
  {
    number: 9,
    name: '小畜',
    pinyin: 'xiǎo xù',
    symbol: '䷈',
    keywords: ['积蓄', '修养', '渐进', '文德'],
    fortune: 'neutral',
  },
  {
    number: 10,
    name: '履',
    pinyin: 'lǚ',
    symbol: '䷉',
    keywords: ['谨慎', '礼节', '以柔克刚', '化险'],
    fortune: 'neutral',
  },
  {
    number: 11,
    name: '泰',
    pinyin: 'tài',
    symbol: '䷊',
    keywords: ['通泰', '和谐', '亨通', '把握机遇'],
    fortune: 'great-fortune',
  },
  {
    number: 12,
    name: '否',
    pinyin: 'pǐ',
    symbol: '䷋',
    keywords: ['闭塞', '韬光养晦', '忍耐', '否极泰来'],
    fortune: 'misfortune',
  },
  {
    number: 13,
    name: '同人',
    pinyin: 'tóng rén',
    symbol: '䷌',
    keywords: ['同心', '合作', '开放', '公心'],
    fortune: 'fortune',
  },
  {
    number: 14,
    name: '大有',
    pinyin: 'dà yǒu',
    symbol: '䷍',
    keywords: ['丰盛', '富有', '光明', '扬善'],
    fortune: 'great-fortune',
  },
  {
    number: 15,
    name: '谦',
    pinyin: 'qiān',
    symbol: '䷎',
    keywords: ['谦逊', '低调', '平衡', '善终'],
    fortune: 'great-fortune',
  },
  {
    number: 16,
    name: '豫',
    pinyin: 'yù',
    symbol: '䷏',
    keywords: ['愉悦', '和谐', '建功', '适度'],
    fortune: 'fortune',
  },
  {
    number: 17,
    name: '随',
    pinyin: 'suí',
    symbol: '䷐',
    keywords: ['随顺', '灵活', '适应', '顺势'],
    fortune: 'fortune',
  },
  {
    number: 18,
    name: '蛊',
    pinyin: 'gǔ',
    symbol: '䷑',
    keywords: ['整治', '改革', '纠偏', '重生'],
    fortune: 'neutral',
  },
  {
    number: 19,
    name: '临',
    pinyin: 'lín',
    symbol: '䷒',
    keywords: ['监临', '把握时机', '居安思危', '教化'],
    fortune: 'fortune',
  },
  {
    number: 20,
    name: '观',
    pinyin: 'guān',
    symbol: '䷓',
    keywords: ['观察', '省察', '领悟', '端正'],
    fortune: 'neutral',
  },
  {
    number: 21,
    name: '噬嗑',
    pinyin: 'shì kè',
    symbol: '䷔',
    keywords: ['果断', '清除障碍', '明辨', '执行'],
    fortune: 'neutral',
  },
  {
    number: 22,
    name: '贲',
    pinyin: 'bì',
    symbol: '䷕',
    keywords: ['修饰', '文饰', '形象', '实质'],
    fortune: 'neutral',
  },
  {
    number: 23,
    name: '剥',
    pinyin: 'bō',
    symbol: '䷖',
    keywords: ['衰退', '蛰伏', '守成', '夯实基础'],
    fortune: 'misfortune',
  },
  {
    number: 24,
    name: '复',
    pinyin: 'fù',
    symbol: '䷗',
    keywords: ['复始', '转机', '新生', '回归'],
    fortune: 'fortune',
  },
  {
    number: 25,
    name: '无妄',
    pinyin: 'wú wàng',
    symbol: '䷘',
    keywords: ['真诚', '无妄', '纯正', '自然'],
    fortune: 'neutral',
  },
  {
    number: 26,
    name: '大畜',
    pinyin: 'dà xù',
    symbol: '䷙',
    keywords: ['大蓄', '厚积薄发', '博学', '出仕'],
    fortune: 'fortune',
  },
  {
    number: 27,
    name: '颐',
    pinyin: 'yí',
    symbol: '䷚',
    keywords: ['颐养', '节制', '自力更生', '修养'],
    fortune: 'neutral',
  },
  {
    number: 28,
    name: '大过',
    pinyin: 'dà guò',
    symbol: '䷛',
    keywords: ['非常', '果断', '独立', '承压'],
    fortune: 'caution',
  },
  {
    number: 29,
    name: '坎',
    pinyin: 'kǎn',
    symbol: '䷜',
    keywords: ['险阻', '诚信', '坚韧', '突破'],
    fortune: 'caution',
  },
  {
    number: 30,
    name: '离',
    pinyin: 'lí',
    symbol: '䷝',
    keywords: ['光明', '柔顺', '附丽', '文明'],
    fortune: 'fortune',
  },
  {
    number: 31,
    name: '咸',
    pinyin: 'xián',
    symbol: '䷞',
    keywords: ['感应', '交流', '真诚', '恋爱'],
    fortune: 'fortune',
  },
  {
    number: 32,
    name: '恒',
    pinyin: 'héng',
    symbol: '䷟',
    keywords: ['持久', '恒心', '坚定', '忠诚'],
    fortune: 'fortune',
  },
  {
    number: 33,
    name: '遁',
    pinyin: 'dùn',
    symbol: '䷠',
    keywords: ['退避', '明哲保身', '远离', '智慧'],
    fortune: 'neutral',
  },
  {
    number: 34,
    name: '大壮',
    pinyin: 'dà zhuàng',
    symbol: '䷡',
    keywords: ['强盛', '力量', '守正', '克制'],
    fortune: 'fortune',
  },
  {
    number: 35,
    name: '晋',
    pinyin: 'jìn',
    symbol: '䷢',
    keywords: ['晋升', '进取', '光明', '展示'],
    fortune: 'fortune',
  },
  {
    number: 36,
    name: '明夷',
    pinyin: 'míng yí',
    symbol: '䷣',
    keywords: ['韬光养晦', '隐忍', '外愚内明', '坚守'],
    fortune: 'caution',
  },
  {
    number: 37,
    name: '家人',
    pinyin: 'jiā rén',
    symbol: '䷤',
    keywords: ['家庭', '和睦', '言行一致', '身教'],
    fortune: 'fortune',
  },
  {
    number: 38,
    name: '睽',
    pinyin: 'kuí',
    symbol: '䷥',
    keywords: ['分歧', '求同存异', '小成', '换位思考'],
    fortune: 'neutral',
  },
  {
    number: 39,
    name: '蹇',
    pinyin: 'jiǎn',
    symbol: '䷦',
    keywords: ['艰难', '反省', '求助', '选择'],
    fortune: 'caution',
  },
  {
    number: 40,
    name: '解',
    pinyin: 'xiè',
    symbol: '䷧',
    keywords: ['解脱', '释放', '宽恕', '速决'],
    fortune: 'fortune',
  },
  {
    number: 41,
    name: '损',
    pinyin: 'sǔn',
    symbol: '䷨',
    keywords: ['减损', '舍得', '克制', '投资'],
    fortune: 'neutral',
  },
  {
    number: 42,
    name: '益',
    pinyin: 'yì',
    symbol: '䷩',
    keywords: ['增益', '进取', '改善', '机遇'],
    fortune: 'great-fortune',
  },
  {
    number: 43,
    name: '夬',
    pinyin: 'guài',
    symbol: '䷪',
    keywords: ['决断', '果断', '公开', '以德服人'],
    fortune: 'neutral',
  },
  {
    number: 44,
    name: '姤',
    pinyin: 'gòu',
    symbol: '䷫',
    keywords: ['邂逅', '警惕', '诱惑', '明辨'],
    fortune: 'caution',
  },
  {
    number: 45,
    name: '萃',
    pinyin: 'cuì',
    symbol: '䷬',
    keywords: ['聚集', '团结', '忧患', '大事'],
    fortune: 'fortune',
  },
  {
    number: 46,
    name: '升',
    pinyin: 'shēng',
    symbol: '䷭',
    keywords: ['上升', '进步', '积累', '循序渐进'],
    fortune: 'great-fortune',
  },
  {
    number: 47,
    name: '困',
    pinyin: 'kùn',
    symbol: '䷮',
    keywords: ['困境', '坚守', '磨炼', '行动'],
    fortune: 'caution',
  },
  {
    number: 48,
    name: '井',
    pinyin: 'jǐng',
    symbol: '䷯',
    keywords: ['初心', '有始有终', '服务', '根基'],
    fortune: 'neutral',
  },
  {
    number: 49,
    name: '革',
    pinyin: 'gé',
    symbol: '䷰',
    keywords: ['变革', '创新', '除旧', '突破'],
    fortune: 'neutral',
  },
  {
    number: 50,
    name: '鼎',
    pinyin: 'dǐng',
    symbol: '䷱',
    keywords: ['更新', '文明', '人才', '开创'],
    fortune: 'great-fortune',
  },
  {
    number: 51,
    name: '震',
    pinyin: 'zhèn',
    symbol: '䷲',
    keywords: ['震动', '警醒', '临危不乱', '成长'],
    fortune: 'neutral',
  },
  {
    number: 52,
    name: '艮',
    pinyin: 'gèn',
    symbol: '䷳',
    keywords: ['静止', '专注', '安住当下', '克制'],
    fortune: 'neutral',
  },
  {
    number: 53,
    name: '渐',
    pinyin: 'jiàn',
    symbol: '䷴',
    keywords: ['渐进', '循序', '耐心', '稳健'],
    fortune: 'fortune',
  },
  {
    number: 54,
    name: '归妹',
    pinyin: 'guī mèi',
    symbol: '䷵',
    keywords: ['审时度势', '安分', '接受', '务实'],
    fortune: 'caution',
  },
  {
    number: 55,
    name: '丰',
    pinyin: 'fēng',
    symbol: '䷶',
    keywords: ['丰盛', '鼎盛', '把握当下', '盛极思变'],
    fortune: 'great-fortune',
  },
  {
    number: 56,
    name: '旅',
    pinyin: 'lǚ',
    symbol: '䷷',
    keywords: ['客旅', '谦卑', '灵活', '守正'],
    fortune: 'neutral',
  },
  {
    number: 57,
    name: '巽',
    pinyin: 'xùn',
    symbol: '䷸',
    keywords: ['柔顺', '渗透', '沟通', '顺从'],
    fortune: 'neutral',
  },
  {
    number: 58,
    name: '兑',
    pinyin: 'duì',
    symbol: '䷹',
    keywords: ['喜悦', '社交', '分享', '学习'],
    fortune: 'fortune',
  },
  {
    number: 59,
    name: '涣',
    pinyin: 'huàn',
    symbol: '䷺',
    keywords: ['涣散', '重聚', '信仰', '精神'],
    fortune: 'neutral',
  },
  {
    number: 60,
    name: '节',
    pinyin: 'jié',
    symbol: '䷻',
    keywords: ['节制', '适度', '规则', '平衡'],
    fortune: 'neutral',
  },
  {
    number: 61,
    name: '中孚',
    pinyin: 'zhōng fú',
    symbol: '䷼',
    keywords: ['诚信', '至诚', '感化', '信任'],
    fortune: 'fortune',
  },
  {
    number: 62,
    name: '小过',
    pinyin: 'xiǎo guò',
    symbol: '䷽',
    keywords: ['低调', '小事', '谦逊', '脚踏实地'],
    fortune: 'neutral',
  },
  {
    number: 63,
    name: '既济',
    pinyin: 'jì jì',
    symbol: '䷾',
    keywords: ['完成', '居安思危', '巩固', '防患'],
    fortune: 'neutral',
  },
  {
    number: 64,
    name: '未济',
    pinyin: 'wèi jì',
    symbol: '䷿',
    keywords: ['未完成', '最后冲刺', '谨慎', '可能性'],
    fortune: 'neutral',
  },
]
