/**
 * gen-feng-mark.ts — emit components/FengMark.tsx from a potrace SVG.
 *
 * Reads a single-path potrace SVG (the traced 甲骨文 phoenix) and writes a
 * react-native-svg component, preserving potrace's flip <g transform> and the
 * raw path so the brushwork is byte-faithful to the trace. Invoked by
 * scripts/gen-feng-mark.sh; not meant to be run by hand.
 *
 *   bun scripts/gen-feng-mark.ts <input.svg> <output.tsx>
 */

import { readFileSync, writeFileSync } from 'node:fs'

const [inPath, outPath] = process.argv.slice(2)
if (!inPath || !outPath) {
  console.error('usage: bun scripts/gen-feng-mark.ts <input.svg> <output.tsx>')
  process.exit(1)
}

const svg = readFileSync(inPath, 'utf8')
const vbMatch = svg.match(/viewBox="([^"]+)"/)
const gMatch = svg.match(/<g\s+transform="([^"]+)"/)
const dMatch = svg.match(/<path[^>]*\sd="([\s\S]*?)"/)
if (!vbMatch || !gMatch || !dMatch) throw new Error('unexpected potrace SVG shape')

const vb = vbMatch[1].split(/\s+/).map(Number)
const [, , W, H] = vb
const transform = gMatch[1]
const d = dMatch[1].replace(/\s+/g, ' ').trim()

const comp = `/**
 * FengMark — the Fēng brand glyph: the oracle-bone (甲骨文) 鳳/風 phoenix.
 *
 * Traced from a rubbing of the 甲骨文 graph (in oracle bone, 風 "wind" and 鳳
 * "phoenix" are the same character — the divine bird whose wingbeat raises the
 * wind). Auto-vectorized (potrace) from the source rubbing, so the brushwork is
 * faithful to the original ink, not a redraw. Single fill path → tints to any
 * brand color (copperGold mark, ink-on-paper icon, etc.). Pure react-native-svg,
 * no Skia / native dep.
 *
 * GENERATED by scripts/gen-feng-mark.sh — do not hand-edit the path; re-run the
 * trace to change it.
 */

import Svg, { G, Path } from 'react-native-svg'
import { FENG_PALETTE } from '@/lib/theme'

const VB_W = ${W}
const VB_H = ${H}
const ASPECT = VB_W / VB_H

interface FengMarkProps {
  /** Rendered height in px. Width follows the glyph's natural aspect ratio. */
  size?: number
  /** Fill color. Defaults to the 铜金 brand mark color. */
  color?: string
}

export function FengMark({ size = 64, color = FENG_PALETTE.copperGold }: FengMarkProps) {
  return (
    <Svg
      width={size * ASPECT}
      height={size}
      viewBox={\`0 0 \${VB_W} \${VB_H}\`}
      accessibilityRole='image'
      accessibilityLabel='Fēng'
    >
      <G transform='${transform}' fill={color}>
        <Path d='${d}' />
      </G>
    </Svg>
  )
}
`

writeFileSync(outPath, comp)
console.log(`wrote ${outPath} (viewBox ${W}x${H}, d ${d.length} chars)`)
