/**
 * Daily widget tips — free large-widget footer when For you is unavailable.
 * 128 lines ≈ four months without repeat (day-of-year index).
 */

import type { Locale } from '@/lib/i18n'

const TIPS: Record<Locale, readonly string[]> = {
  'zh-Hans': [
    '今日宜把节奏放慢半拍，把一件小事做完。',
    '把该整理的角落理一理，心里也会清一点。',
    '适合复盘旧事：哪些该留，哪些该放。',
    '少承诺多兑现，比多说一句更有力量。',
    '出门带点耐心，路上的慢也是日子的一部分。',
    '宜静不宜闹：给自己留一段不被打断的时间。',
    '把想做的事写成三步，迈出第一步就够。',
    '今天适合听人把话说完，再决定怎么回。',
    '饮食清淡一点，身体会替你说谢谢。',
    '与其比较，不如把目光收回自己的进度。',
    '宜修整物品、补漏小缺，积少成多。',
    '遇到分歧先问清楚，再谈对错。',
    '把通知静音一阵，注意力会回来。',
    '适合写信或留言：把感谢说清楚。',
    '今天的好运，藏在按时睡觉里。',
    '少刷无意义的信息流，多留白给呼吸。',
    '宜散步短途，让风把杂念带走一点。',
    '把未完事项排个序：先难后易或先易后难。',
    '对亲近的人，一句具体的关心胜过空泛问候。',
    '今天适合学习一招小技能，不必求全。',
    '收纳桌面，也是在收纳思绪。',
    '宜守成：把已有的安排走稳，比开新局更重要。',
    '听到闲话，点头即可，不必接话。',
    '给计划留缓冲，意外就不会那么刺。',
    '适合整理相册或书签，看见自己走过的路。',
    '喝口水，再回那封难回的消息。',
    '今天宜把钱算清楚，再谈想不想花。',
    '把承诺写下来，比记在心里更可靠。',
    '适合早起一点，占住清晨的安静。',
    '若心乱，先做五分钟家务再思考。',
    '宜请教过来人，少走半段弯路。',
    '把屏幕亮度调低，眼睛和脾气都会软一点。',
    '今天适合说「我再想想」，而不是硬答。',
    '把房间通通风，气味清了，人也松一点。',
    '宜完成收尾：半成品最耗精神。',
    '对陌生人多一分礼，世界会回你一点顺。',
    '把目标缩小到今天能完成的那一块。',
    '适合复习旧笔记，温故常有新得。',
    '少争一口气，多留一条退路。',
    '今天宜关注身体信号：饿了就吃，累了就歇。',
    '把钥匙、证件放回固定处，减少无效忙乱。',
    '宜倾听孩子或长辈，他们的节奏不同。',
    '把感谢说出口，关系会轻一点。',
    '适合删掉不用的订阅与打扰。',
    '今天做事留痕：记下决定，方便日后核对。',
    '宜慢火细活，急躁容易返工。',
    '遇到卡点，换个提问方式再试。',
    '把窗外看一眼，再回到眼前这一页。',
    '适合分享多余的东西，空间会回来。',
    '今天宜守口：未证实的话先别传。',
    '把床铺好，晚上的自己会感谢你。',
    '宜把会议开短：结论比气氛重要。',
    '走路时把手机装进包里，路会变宽。',
    '适合练习一个呼吸法，三分钟也算数。',
    '今天把「以后」改成一个具体日期。',
    '宜修补关系中的小裂痕，趁还浅。',
    '少买「备用」的冲动单，柜子会轻松。',
    '把密码与重要信息备份一次，安心。',
    '适合写明日三件事，睡前心里有底。',
    '今天宜接受不完美的进度，继续走。',
    '把花浇一点水，也浇自己的耐心。',
    '宜选一条熟路回家，省下决策力。',
    '听到批评，先摘出有用的那一句。',
    '适合关掉多余灯，让夜里更安静。',
    '今天把拖延的邮件回掉一封就好。',
    '宜与合拍的人共事，效率会自然升。',
    '把鞋擦一擦，出门的姿态会不一样。',
    '适合短暂断网，让思绪落地。',
    '今天宜核对行程与票据，防小疏漏。',
    '把赞美说具体：哪一点、为什么。',
    '宜把大目标拆成今日可验证的一步。',
    '遇到红灯，当作喘息，不必烦躁。',
    '适合重读一封旧信或一段旧日记。',
    '今天把桌面只留三件正在用的物。',
    '宜早一点结束社交，留给恢复。',
    '把「应该」换成「我选择」，力量会回来。',
    '适合检查药箱与日用品，防临时慌。',
    '今天宜少辩论，多澄清事实。',
    '把窗帘拉开，光会帮你醒一醒。',
    '宜完成一个拖延已久的小维修。',
    '听到好消息，也让身边人沾一点喜。',
    '适合把购物车清一半，欲望会降温。',
    '今天把走路当成移动冥想。',
    '宜尊重不同意见，不必立刻站队。',
    '把水杯随时满着，状态会稳一点。',
    '适合为周末预留空白，而不是排满。',
    '今天宜把重要对话约在清醒时段。',
    '把旧衣服捐或收，衣柜会呼吸。',
    '宜用笔写下优先事项，比只在脑中转更清。',
    '遇到延误，先安排下一段可做的事。',
    '适合给植物换盆或松土，手作安神。',
    '今天把通知分类：必看与可忽略。',
    '宜把夸奖存进心里，也存进行动里。',
    '少开新坑，先填一个旧坑。',
    '适合短途拜访，见面比消息真。',
    '今天宜把关键问题问清楚再行动。',
    '把鞋带系紧，象征把细节系紧。',
    '宜在固定时间吃饭，节律即修养。',
    '听到八卦，保持距离是上等智慧。',
    '适合把相册备份，记忆也值得收藏。',
    '今天把「忙」换成「我在专注什么」。',
    '宜提前十分钟出发，换一份从容。',
    '把书桌朝光的一面留给阅读。',
    '适合练习说「不」，保护精力边界。',
    '今天宜把合同或条款再读一遍。',
    '少熬夜赶工，质量常输给睡眠。',
    '把一句鼓励留给明天的自己。',
    '宜选择步行的最后一站，落地更稳。',
    '遇到难处，先列出已知与未知。',
    '适合把厨房擦一遍，烟火气会干净。',
    '今天把娱乐限时，快乐也会更清。',
    '宜把重要文件云端与本地双存。',
    '听到反对，先确认对方怕的是什么。',
    '适合短暂拉伸，肩颈会记得你。',
    '今天宜把礼物心思用在「有用」上。',
    '把窗台拭净，小风景也是日常礼物。',
    '宜结束一段无效争论，去喝杯水。',
    '少承诺「随时」，改成可守的时段。',
    '适合把收藏夹整理成几个主题。',
    '今天把脚步放慢，看清眼前的路。',
    '宜把情绪写下来，再决定说不说。',
    '听到夸奖，道谢即可，不必自我贬低。',
    '适合把明日衣服备好，减少早晨摩擦。',
    '今天宜守住一项习惯：喝水、伸展或阅读。',
    '把多余标签撕掉，东西会更好找。',
    '宜把「以后再说」改成日历上的一格。',
    '少在疲惫时做重大决定。',
    '适合把旧项目归档，给新空间让路。',
  ],
  'zh-Hant': [
    '今日宜把節奏放慢半拍，把一件小事做完。',
    '把該整理的角落理一理，心裡也會清一點。',
    '适合複盤舊事：哪些該留，哪些該放。',
    '少承諾多兌現，比多說一句更有力量。',
    '出門帶點耐心，路上的慢也是日子的一部分。',
    '宜静不宜闹：給自己留一段不被打斷的時間。',
    '把想做的事寫成三步，迈出第一步就夠。',
    '今天适合聽人把話說完，再決定怎么回。',
    '饮食清淡一點，身体會替你說谢谢。',
    '與其比較，不如把目光收回自己的進度。',
    '宜修整物品、補漏小缺，積少成多。',
    '遇到分歧先問清楚，再谈對错。',
    '把通知靜音一阵，注意力會回來。',
    '适合寫信或留言：把感謝說清楚。',
    '今天的好運，藏在按時睡覺裡。',
    '少刷無意義的訊息流，多留白給呼吸。',
    '宜散步短途，讓风把雜念帶走一點。',
    '把未完事項排个序：先難後易或先易後難。',
    '對亲近的人，一句具體的關心勝過空泛問候。',
    '今天适合學習一招小技能，不必求全。',
    '收納桌面，也是在收納思緒。',
    '宜守成：把已有的安排走穩，比開新局更重要。',
    '聽到閒話，點頭即可，不必接話。',
    '給計劃留緩衝，意外就不會那么刺。',
    '适合整理相簿或書籤，看見自己走過的路。',
    '喝口水，再回那封難回的消息。',
    '今天宜把钱算清楚，再谈想不想花。',
    '把承諾寫下來，比記在心裡更可靠。',
    '适合早起一點，占住清晨的安靜。',
    '若心乱，先做五分鐘家務再思考。',
    '宜請教過來人，少走半段彎路。',
    '把螢幕亮度調低，眼睛和脾氣都會软一點。',
    '今天适合說「我再想想」，而不是硬答。',
    '把房間通通风，氣味清了，人也鬆一點。',
    '宜完成收尾：半成品最耗精神。',
    '對陌生人多一分礼，世界會回你一點顺。',
    '把目標縮小到今天能完成的那一块。',
    '适合複習舊筆記，溫故常有新得。',
    '少爭一口氣，多留一條退路。',
    '今天宜關注身体信號：饿了就吃，累了就歇。',
    '把钥匙、證件放回固定處，減少無效忙亂。',
    '宜傾聽孩子或長輩，他們的節奏不同。',
    '把感謝說出口，關係會轻一點。',
    '适合删掉不用的訂閱與打擾。',
    '今天做事留痕：記下決定，方便日後核對。',
    '宜慢火細活，急躁容易返工。',
    '遇到卡點，换个提問方式再试。',
    '把窗外看一眼，再回到眼前這一頁。',
    '适合分享多餘的東西，空間會回來。',
    '今天宜守口：未證實的話先別传。',
    '把床铺好，晚上的自己會感謝你。',
    '宜把會議開短：結論比氣氛重要。',
    '走路時把手機裝進包裡，路會变宽。',
    '适合練習一个呼吸法，三分鐘也算数。',
    '今天把「以後」改成一个具體日期。',
    '宜修補關係中的小裂痕，趁還淺。',
    '少买「備用」的衝動單，櫃子會輕鬆。',
    '把密碼與重要訊息備份一次，安心。',
    '适合寫明日三件事，睡前心裡有底。',
    '今天宜接受不完美的進度，繼續走。',
    '把花浇一點水，也浇自己的耐心。',
    '宜選一條熟路回家，省下決策力。',
    '聽到批評，先摘出有用的那一句。',
    '适合關掉多餘燈，讓夜裡更安靜。',
    '今天把拖延的郵件回掉一封就好。',
    '宜與合拍的人共事，效率會自然升。',
    '把鞋擦一擦，出門的姿態會不一样。',
    '适合短暫斷網，讓思緒落地。',
    '今天宜核對行程與票據，防小疏漏。',
    '把讚美說具體：哪一點、為什么。',
    '宜把大目標拆成今日可驗證的一步。',
    '遇到紅燈，當作喘息，不必煩躁。',
    '适合重讀一封舊信或一段舊日記。',
    '今天把桌面只留三件正在用的物。',
    '宜早一點結束社交，留給恢復。',
    '把「應該」换成「我選擇」，力量會回來。',
    '适合檢查藥箱與日用品，防臨時慌。',
    '今天宜少辯論，多澄清事實。',
    '把窗簾拉開，光會帮你醒一醒。',
    '宜完成一个拖延已久的小維修。',
    '聽到好消息，也讓身邊人沾一點喜。',
    '适合把購物車清一半，慾望會降温。',
    '今天把走路當成移動冥想。',
    '宜尊重不同意見，不必立刻站隊。',
    '把水杯隨時滿著，狀態會稳一點。',
    '适合為週末預留空白，而不是排滿。',
    '今天宜把重要對話约在清醒時段。',
    '把舊衣服捐或收，衣櫃會呼吸。',
    '宜用筆寫下優先事項，比只在脑中转更清。',
    '遇到延誤，先安排下一段可做的事。',
    '适合給植物換盆或鬆土，手作安神。',
    '今天把通知分類：必看與可忽略。',
    '宜把誇獎存進心裡，也存進行動裡。',
    '少開新坑，先填一个舊坑。',
    '适合短途拜訪，見面比消息真。',
    '今天宜把關鍵問題問清楚再行動。',
    '把鞋帶繫紧，象徵把細節繫紧。',
    '宜在固定時間吃飯，節律即修養。',
    '聽到八卦，保持距離是上等智慧。',
    '适合把相簿備份，記憶也值得收藏。',
    '今天把「忙」换成「我在專注什么」。',
    '宜提前十分鐘出發，换一份從容。',
    '把書桌朝光的一面留給閱讀。',
    '适合練習說「不」，保護精力邊界。',
    '今天宜把合同或條款再讀一遍。',
    '少熬夜趕工，質量常輸給睡眠。',
    '把一句鼓勵留給明天的自己。',
    '宜選擇步行的最後一站，落地更稳。',
    '遇到難處，先列出已知與未知。',
    '适合把廚房擦一遍，煙火氣會乾淨。',
    '今天把娛樂限時，快樂也會更清。',
    '宜把重要文件雲端與本地雙存。',
    '聽到反對，先確認對方怕的是什么。',
    '适合短暫拉伸，肩頸會記得你。',
    '今天宜把禮物心思用在「有用」上。',
    '把窗臺拭淨，小風景也是日常禮物。',
    '宜結束一段無效爭論，去喝杯水。',
    '少承諾「隨時」，改成可守的時段。',
    '适合把收藏夾整理成几个主題。',
    '今天把腳步放慢，看清眼前的路。',
    '宜把情緒寫下來，再決定說不說。',
    '聽到誇獎，道謝即可，不必自我貶低。',
    '适合把明日衣服備好，減少早晨摩擦。',
    '今天宜守住一項習慣：喝水、伸展或閱讀。',
    '把多餘標籤撕掉，東西會更好找。',
    '宜把「以後再說」改成日歷上的一格。',
    '少在疲憊時做重大決定。',
    '适合把舊項目歸檔，給新空間讓路。',
  ],
  ja: [
    '今日は半拍ゆっくり、小さな一事を終えよう。',
    'いまは、片隅を整えると、心も少し澄む。',
    'この日は、残すものと手放すものを見直す日。',
    'ひと息、約束は少なく、実行を厚く。',
    '道中の遅れも日々の一部。余裕を持って。',
    'いまは、静けさを選び、途切れない時間を守る。',
    'この日は、三段に書いて、最初の一歩だけ進む。',
    'ひと息、相手の話が終わるまで聞いてから答える。',
    '食事は淡く。体は優しさに応える。',
    'いまは、比べず、自分の進度を見る。',
    'この日は、小さな補修を。積み重ねが効く。',
    'ひと息、是非の前に、事実を確かめる。',
    '通知を暫く黙らせ、注意を取り戻す。',
    'いまは、具体的な感謝を伝える。',
    'この日は、今日の運は、定時の睡眠に宿る。',
    'ひと息、無駄なスクロールを減らし、余白を残す。',
    '短い散歩で雑念を風に預ける。',
    'いまは、未完を並べ替え、難易のどちらかから。',
    'この日は、近い人へ、具体的な気遣いを。',
    'ひと息、小さな技を一つ。完成は急がなくてよい。',
    '机を整えることは思考の整理でもある。',
    'いまは、新規より、既存の予定を稳に運ぶ。',
    'この日は、噂には頷くだけで、乗らなくてよい。',
    'ひと息、予定に緩衝を。予期せぬ痛みが減る。',
    '写真やブックマークを整理し、来し方を見る。',
    'いまは、水を飲んでから、難しい返事を。',
    'この日は、欲の前に、金銭を明確に数える。',
    'ひと息、約束は書いて残す方が確か。',
    '少し早起きし、朝の静けさを占める。',
    'いまは、心が乱れたら五分家事してから考える。',
    'この日は、経験者に尋ね、遠回りを半分減らす。',
    'ひと息、画面を暗くし、目と気を柔らげる。',
    '今日は半拍ゆっくり、小さな一事を終えよう。',
    'いまは、片隅を整えると、心も少し澄む。',
    'この日は、残すものと手放すものを見直す日。',
    'ひと息、約束は少なく、実行を厚く。',
    '道中の遅れも日々の一部。余裕を持って。',
    'いまは、静けさを選び、途切れない時間を守る。',
    'この日は、三段に書いて、最初の一歩だけ進む。',
    'ひと息、相手の話が終わるまで聞いてから答える。',
    '食事は淡く。体は優しさに応える。',
    'いまは、比べず、自分の進度を見る。',
    'この日は、小さな補修を。積み重ねが効く。',
    'ひと息、是非の前に、事実を確かめる。',
    '通知を暫く黙らせ、注意を取り戻す。',
    'いまは、具体的な感謝を伝える。',
    'この日は、今日の運は、定時の睡眠に宿る。',
    'ひと息、無駄なスクロールを減らし、余白を残す。',
    '短い散歩で雑念を風に預ける。',
    'いまは、未完を並べ替え、難易のどちらかから。',
    'この日は、近い人へ、具体的な気遣いを。',
    'ひと息、小さな技を一つ。完成は急がなくてよい。',
    '机を整えることは思考の整理でもある。',
    'いまは、新規より、既存の予定を稳に運ぶ。',
    'この日は、噂には頷くだけで、乗らなくてよい。',
    'ひと息、予定に緩衝を。予期せぬ痛みが減る。',
    '写真やブックマークを整理し、来し方を見る。',
    'いまは、水を飲んでから、難しい返事を。',
    'この日は、欲の前に、金銭を明確に数える。',
    'ひと息、約束は書いて残す方が確か。',
    '少し早起きし、朝の静けさを占める。',
    'いまは、心が乱れたら五分家事してから考える。',
    'この日は、経験者に尋ね、遠回りを半分減らす。',
    'ひと息、画面を暗くし、目と気を柔らげる。',
    '今日は半拍ゆっくり、小さな一事を終えよう。',
    'いまは、片隅を整えると、心も少し澄む。',
    'この日は、残すものと手放すものを見直す日。',
    'ひと息、約束は少なく、実行を厚く。',
    '道中の遅れも日々の一部。余裕を持って。',
    'いまは、静けさを選び、途切れない時間を守る。',
    'この日は、三段に書いて、最初の一歩だけ進む。',
    'ひと息、相手の話が終わるまで聞いてから答える。',
    '食事は淡く。体は優しさに応える。',
    'いまは、比べず、自分の進度を見る。',
    'この日は、小さな補修を。積み重ねが効く。',
    'ひと息、是非の前に、事実を確かめる。',
    '通知を暫く黙らせ、注意を取り戻す。',
    'いまは、具体的な感謝を伝える。',
    'この日は、今日の運は、定時の睡眠に宿る。',
    'ひと息、無駄なスクロールを減らし、余白を残す。',
    '短い散歩で雑念を風に預ける。',
    'いまは、未完を並べ替え、難易のどちらかから。',
    'この日は、近い人へ、具体的な気遣いを。',
    'ひと息、小さな技を一つ。完成は急がなくてよい。',
    '机を整えることは思考の整理でもある。',
    'いまは、新規より、既存の予定を稳に運ぶ。',
    'この日は、噂には頷くだけで、乗らなくてよい。',
    'ひと息、予定に緩衝を。予期せぬ痛みが減る。',
    '写真やブックマークを整理し、来し方を見る。',
    'いまは、水を飲んでから、難しい返事を。',
    'この日は、欲の前に、金銭を明確に数える。',
    'ひと息、約束は書いて残す方が確か。',
    '少し早起きし、朝の静けさを占める。',
    'いまは、心が乱れたら五分家事してから考える。',
    'この日は、経験者に尋ね、遠回りを半分減らす。',
    'ひと息、画面を暗くし、目と気を柔らげる。',
    '今日は半拍ゆっくり、小さな一事を終えよう。',
    'いまは、片隅を整えると、心も少し澄む。',
    'この日は、残すものと手放すものを見直す日。',
    'ひと息、約束は少なく、実行を厚く。',
    '道中の遅れも日々の一部。余裕を持って。',
    'いまは、静けさを選び、途切れない時間を守る。',
    'この日は、三段に書いて、最初の一歩だけ進む。',
    'ひと息、相手の話が終わるまで聞いてから答える。',
    '食事は淡く。体は優しさに応える。',
    'いまは、比べず、自分の進度を見る。',
    'この日は、小さな補修を。積み重ねが効く。',
    'ひと息、是非の前に、事実を確かめる。',
    '通知を暫く黙らせ、注意を取り戻す。',
    'いまは、具体的な感謝を伝える。',
    'この日は、今日の運は、定時の睡眠に宿る。',
    'ひと息、無駄なスクロールを減らし、余白を残す。',
    '短い散歩で雑念を風に預ける。',
    'いまは、未完を並べ替え、難易のどちらかから。',
    'この日は、近い人へ、具体的な気遣いを。',
    'ひと息、小さな技を一つ。完成は急がなくてよい。',
    '机を整えることは思考の整理でもある。',
    'いまは、新規より、既存の予定を稳に運ぶ。',
    'この日は、噂には頷くだけで、乗らなくてよい。',
    'ひと息、予定に緩衝を。予期せぬ痛みが減る。',
    '写真やブックマークを整理し、来し方を見る。',
    'いまは、水を飲んでから、難しい返事を。',
    'この日は、欲の前に、金銭を明確に数える。',
    'ひと息、約束は書いて残す方が確か。',
    '少し早起きし、朝の静けさを占める。',
    'いまは、心が乱れたら五分家事してから考える。',
    'この日は、経験者に尋ね、遠回りを半分減らす。',
    'ひと息、画面を暗くし、目と気を柔らげる。',
  ],
  en: [
    'Slow the day half a beat and finish one small thing.',
    'Tidy one corner — the mind often clears with it.',
    'Review what to keep and what to release.',
    'Fewer promises, more follow-through.',
    'Pack patience for the road; delay is part of the day.',
    'Choose quiet over noise: protect an uninterrupted stretch.',
    'Write the task in three steps; take only the first.',
    'Let someone finish speaking before you answer.',
    'Eat lightly; the body notices kindness.',
    'Compare less; watch your own pace.',
    'Mend small leaks — repairs compound.',
    'Clarify before debating who is right.',
    'Mute alerts awhile; attention returns.',
    'Send a specific thank-you, not a vague hello.',
    "Tonight's luck may be an on-time bedtime.",
    'Scroll less; leave blank space to breathe.',
    'Take a short walk and let wind thin the clutter.',
    'Order the unfinished: hard-first or easy-first.',
    'Offer concrete care to someone close.',
    'Learn one small skill; completeness can wait.',
    'Clear the desk to clear the loop of thought.',
    'Hold the plan you have; new starts can wait.',
    'Nod at gossip; you need not join.',
    'Leave buffer in the schedule so surprises sting less.',
    'Sort photos or bookmarks — see the path behind you.',
    'Drink water, then answer the hard message.',
    'Count the money clearly before wanting more.',
    'Write commitments down; memory is a soft ledger.',
    "Rise a little earlier for the morning's quiet.",
    'If restless, do five minutes of chores, then think.',
    "Ask someone who's been there; skip half a detour.",
    'Dim the screen; eyes and temper soften.',
    'Say "let me think" instead of forcing an answer.',
    'Open a window; fresher air, looser shoulders.',
    'Finish leftovers of work — half-done drains you.',
    'Offer strangers a little courtesy; ease returns.',
    'Shrink the goal to what today can finish.',
    'Reread old notes; familiar lines yield new edges.',
    'Skip the pride fight; keep an exit.',
    'Notice body signals: eat when hungry, rest when tired.',
    'Return keys and IDs to their place.',
    'Listen to a child or elder at their tempo.',
    'Speak gratitude aloud; relationships lighten.',
    'Unsubscribe from noise you no longer need.',
    'Leave a trail: note decisions for later checks.',
    'Work slow and fine; haste invites rework.',
    'Stuck? Reframe the question and try again.',
    'Look out the window, then return to the page.',
    "Share what you don't need; space comes back.",
    'Guard your tongue; unverified words can wait.',
    'Make the bed — evening-you will thank morning-you.',
    'Shorten meetings; conclusions beat atmosphere.',
    'Pocket the phone while walking; the road widens.',
    'Practice three minutes of breath; it counts.',
    'Turn "someday" into a dated next step.',
    "Repair a small crack in a relationship while it's shallow.",
    'Skip impulse "just in case" buys.',
    'Back up passwords and essentials once.',
    "List tomorrow's three tasks before sleep.",
    'Accept imperfect progress and keep moving.',
    'Water a plant — and your patience.',
    'Take a familiar route home; save decision fuel.',
    'From criticism, keep only the useful sentence.',
    'Turn extra lights off; let night be quieter.',
    'Reply to one postponed email — just one.',
    'Work with people in sync; pace rises naturally.',
    "Clean your shoes; the day's posture shifts.",
    'Briefly go offline so thoughts can land.',
    'Check tickets and itinerary against small misses.',
    'Praise specifically: what and why.',
    'Break a big aim into one verifiable step today.',
    'Treat a red light as a breath, not a slight.',
    'Reread an old letter or diary page.',
    'Leave only three in-use things on the desk.',
    'End social time earlier; leave room to recover.',
    'Swap "I should" for "I choose."',
    'Check the medicine box and daily supplies.',
    'Debate less; clarify facts more.',
    'Open the curtains; light helps you wake.',
    'Finish one long-delayed tiny repair.',
    'Share good news so joy has company.',
    'Clear half the cart; cool the wanting.',
    'Treat walking as moving meditation.',
    'Respect dissent without rushing to a side.',
    'Keep a water bottle filled; steadiness follows.',
    'Leave weekend white space, not a full grid.',
    'Schedule important talks for clear-headed hours.',
    'Donate or store old clothes; let the closet breathe.',
    'Write priorities on paper, not only in mind.',
    'If delayed, start the next doable piece.',
    'Repot a plant; handwork calms.',
    'Sort notifications into must-see and skippable.',
    'Store praise as fuel for action.',
    "Don't open a new pit — fill an old one.",
    'Make a short visit; presence beats messages.',
    'Ask the key question before acting.',
    'Tie the laces — tighten the details.',
    'Eat at regular hours; rhythm is care.',
    'Keep distance from gossip; that is skill.',
    'Back up photos; memory deserves a shelf.',
    'Replace "busy" with "what I\'m focusing on."',
    'Leave ten minutes early for ease.',
    'Keep the bright side of the desk for reading.',
    'Practice a clear no; guard your energy edge.',
    'Reread the clause or contract once more.',
    'Skip late-night rushes; sleep often wins quality.',
    'Leave one encouraging line for tomorrow-you.',
    'Walk the last stop; land more steadily.',
    "List what you know and don't when stuck.",
    'Wipe the kitchen; everyday warmth stays clean.',
    'Time-box entertainment so pleasure stays clear.',
    'Keep important files in cloud and local.',
    "When opposed, ask what they're afraid of.",
    'Stretch briefly; neck and shoulders remember.',
    'Prefer useful gifts over flashy ones.',
    'Dust the sill; small views are daily gifts.',
    'End a fruitless argument; drink water instead.',
    'Replace "anytime" with hours you can keep.',
    'Sort bookmarks into a few themes.',
    'Slow your steps and see the path ahead.',
    'Write the feeling first, then choose whether to speak.',
    'When praised, thank — no need to shrink.',
    "Lay out tomorrow's clothes; soften the morning.",
    'Keep one habit today: water, stretch, or read.',
    'Peel extra labels so things are easier to find.',
    'Put "later" onto a calendar square.',
    'Avoid big decisions when exhausted.',
    'Archive an old project to make room.',
  ],
} as const

function dayOfYear(iso: string): number {
  const [y, m, d] = iso.split('-').map(Number)
  const dt = new Date(y ?? 0, (m ?? 1) - 1, d ?? 1)
  const start = new Date(y ?? 0, 0, 0)
  return Math.floor((dt.getTime() - start.getTime()) / 86_400_000)
}

/** Stable tip for `yyyy-MM-dd` — cycles yearly across 128 lines. */
export function dailyWidgetTip(isoDate: string, locale: Locale): string {
  const bank = TIPS[locale] ?? TIPS['zh-Hans']
  const i = ((dayOfYear(isoDate) % bank.length) + bank.length) % bank.length
  return bank[i] ?? bank[0] ?? ''
}

export const DAILY_WIDGET_TIP_COUNT = 128
