/**
 * 择日宜忌释义 — 术语 → 释义（zh-Hans 来源：维基百科「黄历」条目
 * 「择日宜忌」章，https://zh.wikipedia.org/zh-hans/黄历 ）。
 *
 * 繁体由简体经语料级逐字映射生成（toHant，本文件内表）；en/ja 释义
 * 暂不提供（国际化时参照 Wikipedia 对应语言条目再补）。
 * 点击宜忌词弹出释义用（AlmanacPage / 文化 hub「黄历行话」）。
 */

/** 简体→繁体逐字映射（仅覆盖本语料出现的字）。 */
const S2T: Record<string, string> = {
  说: '說',
  请: '請',
  庙: '廟',
  斋: '齋',
  医: '醫',
  药: '藥',
  坛: '壇',
  龙: '龍',
  华: '華',
  纪: '紀',
  节: '節',
  术: '術',
  师: '師',
  学: '學',
  会: '會',
  亲: '親',
  处: '處',
  仪: '儀',
  迁: '遷',
  众: '眾',
  买: '買',
  产: '產',
  仓: '倉',
  佣: '傭',
  传: '傳',
  伤: '傷',
  丧: '喪',
  为: '為',
  与: '與',
  举: '舉',
  书: '書',
  见: '見',
  应: '應',
  门: '門',
  问: '問',
  开: '開',
  关: '關',
  无: '無',
  体: '體',
  儿: '兒',
  养: '養',
  净: '淨',
  办: '辦',
  动: '動',
  势: '勢',
  厨: '廚',
  启: '啟',
  员: '員',
  周: '週',
  围: '圍',
  国: '國',
  坏: '壞',
  坟: '墳',
  墙: '牆',
  头: '頭',
  婴: '嬰',
  寿: '壽',
  将: '將',
  尸: '屍',
  币: '幣',
  庆: '慶',
  库: '庫',
  征: '徵',
  怀: '懷',
  愿: '願',
  戏: '戲',
  择: '擇',
  攒: '攢',
  数: '數',
  斗: '鬥',
  旧: '舊',
  时: '時',
  机: '機',
  构: '構',
  桥: '橋',
  梁: '樑',
  横: '橫',
  殓: '殮',
  沟: '溝',
  洼: '窪',
  涂: '塗',
  灵: '靈',
  灶: '竈',
  点: '點',
  烧: '燒',
  状: '狀',
  现: '現',
  疗: '療',
  盖: '蓋',
  礼: '禮',
  禅: '禪',
  称: '稱',
  竖: '豎',
  筑: '築',
  结: '結',
  给: '給',
  统: '統',
  纳: '納',
  纹: '紋',
  艺: '藝',
  补: '補',
  装: '裝',
  订: '訂',
  认: '認',
  许: '許',
  讼: '訟',
  设: '設',
  访: '訪',
  诉: '訴',
  购: '購',
  赠: '贈',
  过: '過',
  运: '運',
  还: '還',
  这: '這',
  进: '進',
  远: '遠',
  适: '適',
  选: '選',
  鉴: '鑑',
  针: '針',
  铲: '鏟',
  铺: '鋪',
  间: '間',
  隶: '隸',
  须: '須',
  饰: '飾',
  马: '馬',
  骤: '驟',
  采: '採',
  张: '張',
  业: '業',
  营: '營',
  后: '後',
  腳: '脚',
  烬: '燼',
  复: '復',
  亿: '億',
  样: '樣',
  岁: '歲',
  孙: '孫',
  财: '財',
  贯: '貫',
  宾: '賓',
  实: '實',
  宝: '寶',
  审: '審',
  写: '寫',
  寻: '尋',
  导: '導',
  尽: '盡',
  层: '層',
  届: '屆',
  属: '屬',
  归: '歸',
  当: '當',
  录: '錄',
  彻: '徹',
  忆: '憶',
  忧: '憂',
  惊: '驚',
  担: '擔',
  捡: '撿',
  据: '據',
  挂: '掛',
  换: '換',
  摆: '擺',
  敌: '敵',
  断: '斷',
  族: '族',
  既: '既',
  日: '日',
  旷: '曠',
  旦: '旦',
  曲: '曲',
  权: '權',
  欢: '歡',
  历: '歷',
  灭: '滅',
  汉: '漢',
  泪: '淚',
  测: '測',
  浑: '渾',
  游: '遊',
  烟: '煙',
  热: '熱',
  爱: '愛',
  爷: '爺',
  获: '獲',
  犹: '猶',
  猎: '獵',
  兽: '獸',
  环: '環',
  琐: '瑣',
  献: '獻',
  穷: '窮',
  续: '續',
  继: '繼',
  置: '置',
  义: '義',
  美: '美',
  群: '群',
  習: '習',
  联: '聯',
  声: '聲',
  胆: '膽',
  脸: '臉',
  舞: '舞',
  苦: '苦',
  荆: '荊',
  荐: '薦',
  荣: '榮',
  荧: '熒',
  莲: '蓮',
  萧: '蕭',
  蛮: '蠻',
  術: '術',
  规: '規',
  览: '覽',
  觉: '覺',
  观: '觀',
  记: '記',
  讨: '討',
  让: '讓',
  训: '訓',
  议: '議',
  讯: '訊',
  讶: '訝',
  讷: '訥',
  论: '論',
  讽: '諷',
  诀: '訣',
  证: '證',
  评: '評',
  词: '詞',
  译: '譯',
  试: '試',
  诗: '詩',
  诚: '誠',
  话: '話',
  诞: '誕',
  诡: '詭',
  询: '詢',
  该: '該',
  详: '詳',
  语: '語',
  误: '誤',
  诵: '誦',
  诸: '諸',
  读: '讀',
  课: '課',
  谁: '誰',
  调: '調',
  谈: '談',
  谊: '誼',
  谋: '謀',
  谐: '諧',
  谓: '謂',
  谜: '謎',
  谢: '謝',
  谣: '謠',
  谨: '謹',
  识: '識',
  警: '警',
}

export function toHant(s: string): string {
  return s
    .split('')
    .map((c) => S2T[c] ?? c)
    .join('')
}

const T2S: Record<string, string> = Object.fromEntries(
  Object.entries(S2T).map(([s, t]) => [t, s])
)

/** 繁体 → 简体（用于 en/ja 术语卡对繁体输入的归一）。 */
export function toHans(s: string): string {
  return s
    .split('')
    .map((c) => T2S[c] ?? c)
    .join('')
}

/** 术语 → 简体释义（维基百科「择日宜忌」59 条 + 常用宜忌动词补充 29 条）。 */
const MEANINGS_ZH_HANS: Record<string, string> = {
  纳采: '提亲、说亲',
  问名: '纳采问名、纳采',
  纳吉: '中国传统婚礼中的六礼之一，婚嫁的第三步骤，问名后，男方将男女二人之生辰八字交给算命师，算命师算出二人合适后，男方又去占卜，必须卜得吉兆，然后通知女方，婚姻已定。',
  纳征: '纳币、行聘、订盟、过定、文定、完聘、小聘',
  请期: '中国传统婚礼中的六礼之一，婚嫁的第五步骤，纳征后男方选择结婚日，告之女方，征求女方同意。',
  亲迎: '迎亲、嫁娶',
  裁衣: '主要指剪裁新娘的婚服，另外还指剪裁丧事的寿衣。',
  安床: '指安置床铺。又分安置新床与旧床重新安置。安置新床指嫁娶前男方安置新人房中的床。旧床重新安置是因为运势不佳或女方久久不孕，重新安排过床的位置与方向，以求改运或女方怀孕。',
  开容: '整容、开面',
  入殓: '将尸体放入棺材。',
  移柩: '移动棺材。',
  破土: '掘开土地埋葬死人。',
  安葬: '举行埋葬等仪式。',
  修坟: '修理坟墓。',
  启攒: '指洗骨。',
  祭祀: '指举行社会上的重大祭祀仪式，如政府的封禅、祭天、全宗族数百人的祠祭仪式等。如果是日常一般烧香拜神祭祖，或民间年节、神佛生日、得道日等庆典，或是先人生辰、忌日等纪念日等，皆不在此限。',
  祈福: '指庙方作醮、举办法会，一说是“请他庙神灵鉴醮”或“祭星、拜斗”等等仪式。一般民众向家中神佛、祖先祈求平安，或到庙中礼佛拜神、许愿还愿、演戏酬神、祈求好运等，皆不在此限。',
  开光: '神像、佛像塑成后、供奉上位之事。',
  入宅: '家庭搬入新屋，或机构迁至新址，以祭神仪式为起始点，称作“入厝仪式”。故民间通常是搬家前择取吉日，举办“入厝仪式”。亦有人在搬家后，才择取吉日，举办“入厝仪式”。',
  破屋坏垣: '拆除房屋与围墙，垣的意思为围墙。',
  拆卸: '拆除建筑物。',
  动土: '建筑房屋时、第一次挖土。填平洼地或铲平凸地时亦在此列。',
  起基: '起基定磉（磉为柱子下面的石头）',
  架马: '起工架马',
  盖屋: '盖屋合脊、盖屋泥壁、盖屋泥饰',
  垣墙: '建造建筑物四周的围墙。',
  平治道涂: '将建筑物四周的道路铺平。',
  伐木: '伐木作粱、入山伐木',
  开柱: '开柱眼，在粱柱上面开洞。',
  定梁: '固定梁木。',
  竖柱上梁: '竖立柱子，上置横梁。',
  作灶: '安修厨灶',
  安磨: '安装石磨等用具。',
  造仓: '造仓库',
  斋醮: '庙宇建醮前需举行的斋戒仪式。',
  造庙: '建造宗祠，寺庙等建筑物',
  修仓: '修仓库',
  补垣塞穴: '修补墙上的洞穴。',
  补垣墙: '修饰垣墙',
  置产: '修置产室',
  买宅受田: '购买住宅与田地，或接收赠送的住宅与田地。',
  造桥: '建筑桥梁。',
  开渠: '建造建筑物内或附近的水沟，现代包括下水道。',
  开池: '开挖池塘。',
  作陂: '陂池即蓄水池，建造蓄水池。',
  放水: '开渠放水',
  筑堤: '修筑堤防。',
  分居: '指大家族分家，成员搬至他处定居。',
  进人口: '认养养子；增添家佣、奴婢。',
  整手足甲: '剪指甲与脚甲，主要指婴儿的首次做这些事。',
  沐浴: '即洗澡，主要指斋戒沐浴净身，也指婴儿首次洗身。',
  求医疗病: '求医治疗或动手术。',
  疗目: '治疗眼睛。',
  针刺: '指针灸，或给奴隶纹身。',
  入学: '指幼儿第一次进入学校或学堂等接受教育、拜师学艺。',
  会亲友: '拜访亲友，或设宴款待亲友。',
  进寿: '做生日',
  出行: '出外远行，旅行。',
  诉讼: '打官司，起诉状。',
  嫁娶: '男女结为夫妻、举行婚礼。',
  开市: '商店开张营业，公司、工坊开始营业。',
  立券: '订立契约，签立合同文书。',
  交易: '买卖双方交换货物钱财。',
  纳财: '收取货款、收账、置产进货等进财之事。',
  移徙: '搬家迁移住所，由旧居迁入新居。',
  见贵: '拜见贵人、上司或重要人物。',
  求财: '谋求钱财，经营求利。',
  求嗣: '祈求子嗣。',
  安香: '安奉神位香火。',
  经络: '针灸、推拿等调理经络气血之事。',
  牧养: '饲养家畜。',
  纳畜: '买入牲畜。',
  捕捉: '捕拿猎物、擒拿。',
  畋猎: '打猎。',
  取鱼: '捕鱼。',
  栽种: '种植作物苗木。',
  解除: '解除灾厄、清洗污秽、断除关系。',
  谢土: '酬谢土地神，竣工后祭祀。',
  上梁: '安装房屋大梁。',
  修饰垣墙: '修缮围墙。',
  入仓: '粮食货物入库存放。',
  登高: '登山远足。',
  行船: '船只航行。',
  涂泥: '抹泥修补。',
  除服: '服丧期满，除去丧服。',
  治病: '看病服药。',
  雕刻: '雕刻玉石木器等。',
  理发: '修剪头发。',
}

const MEANINGS_ZH_HANT: Record<string, string> = Object.fromEntries(
  Object.entries(MEANINGS_ZH_HANS).map(([k, v]) => [toHant(k), toHant(v)])
)

/** 按维基章节分组的术语顺序（用于文化 hub 展示）。 */
export const YIJI_MEANING_GROUPS: Array<{ title: string; terms: readonly string[] }> = [
  {
    title: '冠婚丧祭',
    terms: [
      '纳采',
      '问名',
      '纳吉',
      '纳征',
      '请期',
      '亲迎',
      '裁衣',
      '安床',
      '开容',
      '入殓',
      '移柩',
      '破土',
      '安葬',
      '修坟',
      '启攒',
    ],
  },
  {
    title: '建筑 · 搬迁',
    terms: [
      '祭祀',
      '祈福',
      '开光',
      '入宅',
      '破屋坏垣',
      '拆卸',
      '动土',
      '起基',
      '架马',
      '盖屋',
      '垣墙',
      '平治道涂',
      '伐木',
      '开柱',
      '定梁',
      '竖柱上梁',
      '作灶',
      '安磨',
      '造仓',
      '斋醮',
      '造庙',
      '修仓',
      '补垣塞穴',
      '补垣墙',
      '置产',
      '买宅受田',
      '造桥',
      '开渠',
      '开池',
      '作陂',
    ],
  },
  {
    title: '生活起居 · 仪式庆典',
    terms: [
      '放水',
      '筑堤',
      '分居',
      '进人口',
      '整手足甲',
      '沐浴',
      '求医疗病',
      '疗目',
      '针刺',
      '入学',
      '会亲友',
      '进寿',
      '出行',
      '诉讼',
    ],
  },
]

/** 术语国际卡 — 拼音 + en/ja 一句话释义（Wikipedia 无术语级条目时的
 *  自写白话口径；原文照录 + 读音）。 */
const PY: Record<string, string> = {
  '纳采': "nàcǎi",
  '问名': "wènmíng",
  '纳吉': "nàjí",
  '纳征': "nàzhēng",
  '请期': "qǐngqī",
  '亲迎': "qīnyíng",
  '裁衣': "cáiyī",
  '安床': "ānchuáng",
  '开容': "kāiróng",
  '入殓': "rùliàn",
  '移柩': "yíjiù",
  '破土': "pòtǔ",
  '安葬': "ānzàng",
  '修坟': "xiūfén",
  '启攒': "qǐcuán",
  '祭祀': "jìsì",
  '祈福': "qífú",
  '开光': "kāiguāng",
  '入宅': "rùzhái",
  '破屋坏垣': "pòwūhuàiyuán",
  '拆卸': "chāixiè",
  '动土': "dòngtǔ",
  '起基': "qǐjī",
  '架马': "jiàmǎ",
  '盖屋': "gàiwū",
  '垣墙': "yuánqiáng",
  '平治道涂': "píngzhìdàotú",
  '伐木': "fámù",
  '开柱': "kāizhù",
  '定梁': "dìngliáng",
  '竖柱上梁': "shùzhùshàngliáng",
  '作灶': "zuòzào",
  '安磨': "ānmò",
  '造仓': "zàocāng",
  '斋醮': "zhāijiào",
  '造庙': "zàomiào",
  '修仓': "xiūcāng",
  '补垣塞穴': "bǔyuánsèxué",
  '补垣墙': "bǔyuánqiáng",
  '置产': "zhìchǎn",
  '买宅受田': "mǎizháishòutián",
  '造桥': "zàoqiáo",
  '开渠': "kāiqú",
  '开池': "kāichí",
  '作陂': "zuòbēi",
  '放水': "fàngshuǐ",
  '筑堤': "zhùdī",
  '分居': "fēnjū",
  '进人口': "jìnrénkǒu",
  '整手足甲': "zhěngshǒuzújiǎ",
  '沐浴': "mùyù",
  '求医疗病': "qiúyīliáobìng",
  '疗目': "liáomù",
  '针刺': "zhēncì",
  '入学': "rùxué",
  '会亲友': "huìqīnyǒu",
  '进寿': "jìnshòu",
  '出行': "chūxíng",
  '诉讼': "sùsòng",
  '嫁娶': "jiàqǔ",
  '开市': "kāishì",
  '立券': "lìquàn",
  '交易': "jiāoyì",
  '纳财': "nàcái",
  '移徙': "yíxǐ",
  '见贵': "jiànguì",
  '求财': "qiúcái",
  '求嗣': "qiúsì",
  '安香': "ānxiāng",
  '经络': "jīngluò",
  '牧养': "mùyǎng",
  '纳畜': "nàchù",
  '捕捉': "bǔzhuō",
  '畋猎': "tiánliè",
  '取鱼': "qǔyú",
  '栽种': "zāizhòng",
  '解除': "jiěchú",
  '谢土': "xiètǔ",
  '上梁': "shàngliáng",
  '修饰垣墙': "xiūshìyuánqiáng",
  '入仓': "rùcāng",
  '登高': "dēnggāo",
  '行船': "xíngchuán",
  '涂泥': "túní",
  '除服': "chúfú",
  '治病': "zhìbìng",
  '雕刻': "diāokè",
  '理发': "lǐfà",
}

const EN: Record<string, string> = {
  '纳采': "Betrothal gifts — the first formal step of the wedding rites.",
  '问名': "Asking the bride’s name and birth data (wedding-rites step 2).",
  '纳吉': "Checking the couple’s charts and announcing the match (step 3).",
  '纳征': "Sending betrothal gifts to seal the engagement (step 4).",
  '请期': "Agreeing the wedding date with the bride’s family (step 5).",
  '亲迎': "The groom fetches the bride (step 6).",
  '裁衣': "Cutting the wedding (or funeral) garments.",
  '安床': "Placing the bed — the bridal bed, or re-placing a bed for better luck.",
  '开容': "The bride’s pre-wedding make-up rite.",
  '入殓': "Placing the body into the coffin.",
  '移柩': "Moving the coffin.",
  '破土': "The first digging of a grave.",
  '安葬': "The burial rites.",
  '修坟': "Repairing a grave.",
  '启攒': "Exhuming and washing the bones.",
  '祭祀': "Major sacrificial rites — state, clan or ancestral.",
  '祈福': "Praying for blessings — temple rites, vows, thanks.",
  '开光': "Consecrating a newly made deity statue.",
  '入宅': "Moving into a new home, with the house-warming rite.",
  '破屋坏垣': "Demolishing buildings and walls.",
  '拆卸': "Dismantling structures.",
  '动土': "The first ground-breaking for construction.",
  '起基': "Laying the foundation.",
  '架马': "Erecting the scaffolding.",
  '盖屋': "Roofing and finishing the house.",
  '垣墙': "Building surrounding walls.",
  '平治道涂': "Leveling the roads around a building.",
  '伐木': "Felling timber.",
  '开柱': "Cutting mortises in pillars.",
  '定梁': "Fixing the roof beams.",
  '竖柱上梁': "Raising pillars and placing beams.",
  '作灶': "Building the kitchen stove.",
  '安磨': "Installing millstones.",
  '造仓': "Building a granary.",
  '斋醮': "The purification rites before a temple jiao.",
  '造庙': "Building shrines and temples.",
  '修仓': "Repairing a granary.",
  '补垣塞穴': "Mending walls and plugging holes.",
  '补垣墙': "Repairing the walls.",
  '置产': "Preparing the birthing room.",
  '买宅受田': "Buying or receiving houses and fields.",
  '造桥': "Building bridges.",
  '开渠': "Digging water channels.",
  '开池': "Digging ponds.",
  '作陂': "Building reservoirs.",
  '放水': "Releasing water through channels.",
  '筑堤': "Building dykes.",
  '分居': "Splitting a large family household.",
  '进人口': "Adopting a child or adding servants.",
  '整手足甲': "The first trimming of an infant’s nails.",
  '沐浴': "Ritual bathing — purification, or an infant’s first bath.",
  '求医疗病': "Seeing a doctor, treatment or surgery.",
  '疗目': "Treating the eyes.",
  '针刺': "Acupuncture and moxibustion.",
  '入学': "Starting school or formal study.",
  '会亲友': "Visiting or hosting family and friends.",
  '进寿': "Celebrating a birthday.",
  '出行': "Travel and long journeys.",
  '诉讼': "Lawsuits and legal action.",
  '嫁娶': "Marriage — the wedding rites.",
  '开市': "Opening a shop or business.",
  '立券': "Signing contracts.",
  '交易': "Trade — buying and selling.",
  '纳财': "Receiving money — collecting debts, stocking goods.",
  '移徙': "Moving house.",
  '见贵': "Meeting nobles, superiors or important people.",
  '求财': "Seeking wealth and profit.",
  '求嗣': "Praying for offspring.",
  '安香': "Enshrining the incense altar.",
  '经络': "Meridian care — acupuncture and massage.",
  '牧养': "Keeping livestock.",
  '纳畜': "Buying livestock.",
  '捕捉': "Catching game or quarry.",
  '畋猎': "Hunting.",
  '取鱼': "Fishing.",
  '栽种': "Planting crops and trees.",
  '解除': "Dispelling misfortune, cleansing, severing ties.",
  '谢土': "Thanking the earth god after construction.",
  '上梁': "Raising the main roof beam.",
  '修饰垣墙': "Repairing the walls.",
  '入仓': "Storing grain and goods.",
  '登高': "Climbing heights — hiking.",
  '行船': "Sailing.",
  '涂泥': "Plastering with mud.",
  '除服': "Laying aside mourning dress.",
  '治病': "Medical treatment.",
  '雕刻': "Carving jade, wood or stone.",
  '理发': "Haircut.",
}

const JA: Record<string, string> = {
  '纳采': "納采（のうさい）— 婚約の最初の儀礼。結納を贈る。",
  '问名': "問名（ぶんめい）— 六礼の第二。名と生まれを問う。",
  '纳吉': "納吉（のうきつ）— 相性を占い、吉を得て婚約を知らせる。",
  '纳征': "納征（のうちょう）— 結納を納めて婚約を固める。",
  '请期': "請期（せいき）— 日取りを女方に告げ、同意を得る。",
  '亲迎': "親迎（しんげい）— 新郎が新婦を迎える。",
  '裁衣': "裁衣（さいい）— 婚礼・喪服の衣を裁つ。",
  '安床': "安床（あんしょう）— 寝床を据える。新婚の床、または運気改善の据え直し。",
  '开容': "開容（かいよう）— 花嫁の化粧（開面）の儀。",
  '入殓': "入殮（にゅうれん）— 遺体を棺に納める。",
  '移柩': "移柩（いきゅう）— 棺を移す。",
  '破土': "破土（はど）— 埋葬のための最初の掘削。",
  '安葬': "安葬（あんそう）— 埋葬の儀。",
  '修坟': "修墳（しゅうふん）— 墓を修繕する。",
  '启攒': "啓攢（けいさん）— 洗骨・改葬。",
  '祭祀': "祭祀（さいし）— 神や祖先への祭祀。",
  '祈福': "祈福（きふく）— 福を祈る。願掛け。",
  '开光': "開光（かいこう）— 新たな神像を開眼供養する。",
  '入宅': "入宅（にゅうたく）— 新居への転居（入居の儀）。",
  '破屋坏垣': "破屋壊垣（はおくかいえん）— 家屋や塀を取り壊す。",
  '拆卸': "拆卸（てっしゃ）— 建物を解体する。",
  '动土': "動土（どうど）— 建築の最初の掘削。",
  '起基': "起基（きき）— 基礎を据える。",
  '架马': "架馬（かば）— 足場を組む。",
  '盖屋': "蓋屋（がいおく）— 屋根を葺き、家を仕上げる。",
  '垣墙': "垣牆（えんしょう）— 周囲の塀を築く。",
  '平治道涂': "平治道塗（へいちどうと）— 建物周りの道を平らにする。",
  '伐木': "伐木（ばつぼく）— 木材を伐採する。",
  '开柱': "開柱（かいちゅう）— 柱に穴を開ける。",
  '定梁': "定梁（ていりょう）— 梁を固定する。",
  '竖柱上梁': "立柱上梁（りっちゅうじょうりょう）— 柱を立て梁を上げる。",
  '作灶': "作竈（さくそう）— かまどを据える。",
  '安磨': "安磨（あんま）— 石臼を据える。",
  '造仓': "造倉（ぞうそう）— 倉を建てる。",
  '斋醮': "斎醮（さいしょう）— 斎戒のうえ神を祀る。",
  '造庙': "造廟（ぞうびょう）— 廟を建てる。",
  '修仓': "修倉（しゅうそう）— 倉を修繕する。",
  '补垣塞穴': "補垣塞穴（ほえんそくけつ）— 塀を補い、穴を塞ぐ。",
  '补垣墙': "補垣牆（ほえんしょう）— 塀を修繕する。",
  '置产': "置産（ちさん）— 産室を整える。",
  '买宅受田': "買宅受田（ばいたくじゅでん）— 家や田畑を購入・譲受する。",
  '造桥': "造橋（ぞうきょう）— 橋を架ける。",
  '开渠': "開渠（かいきょ）— 水路を掘る。",
  '开池': "開池（かいち）— 池を掘る。",
  '作陂': "作陂（さくひ）— ため池を築く。",
  '放水': "放水（ほうすい）— 水路に水を流す。",
  '筑堤': "築堤（ちくてい）— 堤防を築く。",
  '分居': "分居（ぶんきょ）— 大家族の分家。",
  '进人口': "進人口（しんじんこう）— 養子・奉公人を迎える。",
  '整手足甲': "整手足甲（せいしゅそくこう）— 嬰児の初めての爪切り。",
  '沐浴': "沐浴（もくよく）— 沐浴。身を清める。",
  '求医疗病': "求医療病（きゅういりょうびょう）— 医者にかかり治療する。",
  '疗目': "療目（りょうもく）— 目の治療。",
  '针刺': "針刺（しんし）— 鍼灸。",
  '入学': "入学（にゅうがく）— 入学・入門。",
  '会亲友': "会親友（かいしんゆう）— 親戚友人と会う・もてなす。",
  '进寿': "進寿（しんじゅ）— 誕生日の祝い。",
  '出行': "出行（しゅつこう）— 遠出・旅行。",
  '诉讼': "訴訟（そしょう）— 訴訟を起こす。",
  '嫁娶': "嫁娶（かしゅ）— 結婚の儀。",
  '开市': "開市（かいし）— 開店・開業。",
  '立券': "立券（りっけん）— 契約を結ぶ。",
  '交易': "交易（こうえき）— 売買・取引。",
  '纳财': "納財（のうざい）— 金を納める。入金・集金。",
  '移徙': "移徙（いし）— 転居・引っ越し。",
  '见贵': "見貴（けんき）— 貴人・上司に会う。",
  '求财': "求財（ぐざい）— 財を求める。",
  '求嗣': "求嗣（ぐし）— 子宝を祈る。",
  '安香': "安香（あんこう）— 神位を安置する。",
  '经络': "経絡（けいらく）— 鍼灸・按摩で気血を整える。",
  '牧养': "牧養（ぼくよう）— 家畜を飼う。",
  '纳畜': "納畜（のうちく）— 家畜を買い入れる。",
  '捕捉': "捕捉（ほそく）— 獲物を捕らえる。",
  '畋猎': "畋猟（でんりょう）— 狩猟。",
  '取鱼': "取魚（しゅぎょ）— 漁。",
  '栽种': "栽種（さいしゅ）— 植え付け。",
  '解除': "解除（かいじょ）— 厄を祓い、清める。",
  '谢土': "謝土（しゃど）— 工事の後、土の神に謝す。",
  '上梁': "上梁（じょうりょう）— 棟上げ。",
  '修饰垣墙': "修飾垣牆（しゅうしょくえんしょう）— 塀を修繕する。",
  '入仓': "入倉（にゅうそう）— 倉に納める。",
  '登高': "登高（とうこう）— 高きに登る。",
  '行船': "行船（こうせん）— 船を出す。",
  '涂泥': "塗泥（とでい）— 泥を塗る。",
  '除服': "除服（じょふく）— 喪服を脱ぐ。服喪明け。",
  '治病': "治病（ちびょう）— 病を治す。",
  '雕刻': "雕刻（ちょうこく）— 彫刻。",
  '理发': "理髪（りはつ）— 散髪。",
}

const TERM_PINYIN: Record<string, string> = PY
const TERM_EN: Record<string, string> = EN
const TERM_JA: Record<string, string> = JA

export function yijiTermPinyin(term: string): string | null {
  return TERM_PINYIN[term] ?? TERM_PINYIN[toHant(term)] ?? TERM_PINYIN[toHans(term)] ?? null
}

/** 取释义（四语）：zh 原文简/繁；en = 拼音 + 英文释义（无则原文+拼音）；
 *  ja = 日文释义（无则原文）。 */
export function yijiMeaning(term: string, locale: string): string | null {
  if (locale.startsWith('zh-Hant') || locale.includes('hant')) {
    return MEANINGS_ZH_HANT[term] ?? MEANINGS_ZH_HANT[toHant(term)] ?? null
  }
  if (locale.startsWith('ja')) {
    return (
      TERM_JA[term] ??
      TERM_JA[toHant(term)] ??
      TERM_JA[toHans(term)] ??
      MEANINGS_ZH_HANS[term] ??
      null
    )
  }
  if (locale.startsWith('en')) {
    const pinyin = TERM_PINYIN[term] ?? TERM_PINYIN[toHant(term)] ?? TERM_PINYIN[toHans(term)]
    const en = TERM_EN[term] ?? TERM_EN[toHant(term)] ?? TERM_EN[toHans(term)]
    if (en && pinyin) return `${pinyin} · ${en}`
    const hans = MEANINGS_ZH_HANS[term] ?? MEANINGS_ZH_HANS[toHans(term)]
    return pinyin ? `${pinyin} · ${hans ?? term}` : (en ?? hans ?? null)
  }
  return MEANINGS_ZH_HANS[term] ?? null
}

export const hasYijiMeaning = (term: string): boolean => term in MEANINGS_ZH_HANS
