/**
 * Generated by `bun types` (wrangler types). Hand-maintained in V1 because
 * the actual generator wasn't run during scaffold. Once the worker is first
 * deployed locally, replace with the auto-generated file.
 */

declare global {
  interface Env {
    ENV: 'production' | 'preview' | 'development'
    /** Default Mapbox style for static-image requests, e.g. "mapbox/satellite-v9". */
    MAPBOX_STATIC_STYLE: string

    // ── Secrets (set via `wrangler secret put`) ──────────────────────────
    /** Mapbox access token (sk.* or pk.* — needs static-images:read scope). */
    MAPBOX_TOKEN: string
    /** Gemini API key — VLM (Stage-1 vision) ONLY. Text synthesis runs on Workers AI. */
    GEMINI_API_KEY: string
    /**
     * Mapillary access token (OPTIONAL). When set, /street/sha pulls street-level
     * imagery for 小峦头 形煞 detection. Unset = feature off (degraded). Mapillary
     * imagery is CC-BY-SA — attribution MUST be shown wherever it is surfaced, and
     * derived-use must be legally confirmed before enabling in production.
     */
    MAPILLARY_TOKEN?: string

    // ── Workers AI ───────────────────────────────────────────────────────
    /** Cloudflare Workers AI binding — Stage-3 text synthesis via @zhop/ai-vision/router. */
    AI: Ai

    // ── R2 buckets ───────────────────────────────────────────────────────
    /** Raw Mapbox PNGs keyed by hash(lat,lng,zoom,size,mode,style). */
    MAPS_CACHE: R2Bucket
    /** Server-annotated PNGs (with arrows + bagua overlay). */
    ANNOTATED_CACHE: R2Bucket
  }
}

export {}
